### ISSUE TITLE
#1 Git и Github

### ISSUE THREAD

**Issue by Dosant** [chenyavdv/EP2017#1]
Привет, 
Вроде .gitignore ок, но он почему-то не сработал и в папке taks1 оказались лишние файлы от идеи.

Скорее всего вы сначала добавили эти файлы в git, а потом заигнорили их. 
Я думаю, чтобы их убрать, придется:
1. удалить gitignore, закоммитеть удаление.
2. удалить мусорный файлы, закоммитеть удаление.
3. опять добавить .gitignore.

**Comment by chenyavdv** [comment]
Мусорные файлы - это те, которые остались от идеи?

**Comment by chenyavdv** [comment]
Исправил
