### ISSUE TITLE
#2 Прототипирование интерфейса

### ISSUE THREAD

**Issue by Dosant** [chenyavdv/EP2017#2]
1. язык интерфейса в ТЗ - русский
2. картинок в тз нету, делать необязательно
3. Вряд ли понадобится отдельная кнопка в хедере, Edit News. Эта кнопка скорее должна относиться к каждой отдельной новости (Может где-то на экране детального просмотра новости).

**Comment by chenyavdv** [comment]
1. Язык интерфейса будет русским. При разработке вайерфрейма совершенно вылетело из головы.
2. Но всё-таки с картинками сайт выглядит более красочным и законченным. Если в дальнейшем возникнут трудности, то картинки будут убраны.
3. Согласен. Исправлю при верстке.
