### ISSUE TITLE
#3 Верстка

### ISSUE THREAD

**Issue by chenyavdv** [chenyavdv/EP2017#3]
К сожалению в срок выполнить задание не успел
Задание #3 и #4 сдам до 06.08.2017

**Comment by chenyavdv** [comment]
Сделал абсолютно не по вайерфрейму, потому что вайерфрейм изначально был сделан в книжной ориентации. При верстке обнаружил, что исходя из альбомной ориентации экрана компьютера можно использовать пространство  более грамотно.

**Comment by aaneitchik** [comment]
\+

1. html lang="ru" :+1: 
2. id не должны дублироваться в html. id - уникальный идентификатор
