### ISSUE TITLE
Конец семестра

### ISSUE THREAD

**Issue by aaneitchik** [chenyavdv/EP2017#6]
привет! семестр заканчивается, в следующий вторник будут последние 2 занятия, оба по практике. если хочешь поднять оценку (а с 4 выполненными заданиями она не очень высокая), то к следующему разу настоятельно рекомендую сделать хотя бы фронтенд полностью (задание 6 включительно). задания 9 - 10 тоже простые и быстро делаются, можно еще набрать баллов за счет них.

**Comment by chenyavdv** [comment]
Спасибо за информацию!

**Comment by chenyavdv** [comment]
@aaneitchik 
Добавил задания 1-7.
На зачете буду отсутствовать в силу гос экзамена на военной кафедре, поэтому назрел вопрос: как в таком случае получать зачет по учебной практике? 😢

**Comment by chenyavdv** [comment]
@aaneitchik 
PS последнее добавление сделано с другого моего аккаунта, вероятно ошибся при использовании консоли git

**Comment by aaneitchik** [comment]
1-7 проверили, поставили 7 итоговую, в ведомость оценку преподы тоже поставили. тебе нужно будет своего преподавателя по практике найти, чтобы он/она расписались и в зачетке.
